import type { Metadata } from 'next'
import StyledComponentsProvider from '@/providers/styledComponentsProvider'
import { Inter } from 'next/font/google'
import { ProviderThemeContext } from '@/context/ThemeContext'
import { ReactQueryProvider } from '@/providers/ReactQueryProvider'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <ProviderThemeContext>
            <StyledComponentsProvider>{children}</StyledComponentsProvider>
            <ToastContainer />
          </ProviderThemeContext>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
