import type { Metadata } from 'next'
import StyledComponentsProvider from '@/providers/styledComponentsProvider'
import { Inter } from 'next/font/google'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { Providers } from '@/providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Github Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StyledComponentsProvider>{children}</StyledComponentsProvider>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  )
}
